# frozen_string_literal: true

VALID_EMAILS = [
  'valid@example.com',
  'Valid@test.example.com',
  'valid+valid123@test.example.com',
  'valid_valid123@test.example.com',
  'valid-valid+123@test.example.co.uk',
  'valid-valid+1.23@test.example.com.au',
  'valid@example.co.uk',
  'v@example.com',
  'valid@example.ca',
  'valid_@example.com',
  'valid123.456@example.org',
  'valid123.456@example.travel',
  'valid123.456@example.museum',
  'valid@example.mobi',
  'valid@example.info',
  'valid-@example.com',
  'fake@p-t.k12.ok.us',
  'valid@mail.x.example.com',
  'valid@x.com',
  'valid@example.w-dash.sch.uk',
  'customer/department=shipping@example.com',
  '$A12345@example.com',
  '!def!xyz%abc@example.com',
  '_somename@example.com',
  "test'test@example.com",
  'test@xn--bcher-kva.ch',
  'test@example.xn--0zwm56d',
  'test@192.192.192.1'
].freeze

INVALID_EMAILS = [
  'no_at_symbol',
  'invalid@ex_mple.com',
  'invalid@e..example.com',
  'invalid@p-t..example.com',
  'invalid@example.com.',
  'invalid@example.com_',
  'invalid@example.com-',
  'invalid-example.com',
  'invalid@example.b#r.com',
  'invali d@example.com',
  '"a-17180061943-10618354-1993365053@example.com',
  'invalidexample.com',
  'local@sub.)domain.com',
  'local@sub.#domain.com',
  "foo@example.com\nexample@gmail.com",
  'invalid@example.',
  '"foo\\\\""@bar.com',
  "foo@mail.com\r\nfoo@mail.com",
  '@example.com',
  'foo@',
  'foo',
  'Iñtërnâtiônàlizætiøn@hasnt.happened.to.email',
  'Fred\ Bloggs_@example.com',
  'Abc\@def+@example.com',
  'Joe.\\Blow@example.com',
  %("example\\\\""example.com)
].freeze
